name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: flowscan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "VISION_KEY=${{ secrets.VISION_KEY }}" >> .env
          echo "VISION_ENDPOINT=${{ secrets.VISION_ENDPOINT }}" >> .env
          echo "REACT_APP_ENV=production" >> .env
          echo "REACT_APP_AWS_ACCESS_KEY_ID=${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}" >> .env
          echo "REACT_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "REACT_APP_AWS_BUCKET_NAME=${{ secrets.REACT_APP_AWS_BUCKET_NAME }}" >> .env
          echo "REACT_APP_AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }}" >> .env
          echo "REACT_APP_API_URL=https://${{ secrets.EC2_DOMAIN }}/api" >> .env
          echo "REACT_APP_IMG_URL=${{ secrets.REACT_APP_IMG_URL }}" >> .env
    
      - name: Verify secrets presence
        run: |
          echo "Testing if secrets are accessible..."
          if [ -n "${{ secrets.EC2_HOST }}" ]; then
            echo "✅ EC2_HOST secret exists"
          else
            echo "❌ EC2_HOST secret is empty or inaccessible"
          fi
          
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "✅ SSH_PRIVATE_KEY secret exists"
          else
            echo "❌ SSH_PRIVATE_KEY secret is empty or inaccessible"
          fi

      - name: Set up SSH with fixed host
        run: |
          mkdir -p ~/.ssh
          
          # Use the SSH key from secrets
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Hardcode the EC2 IP for testing (remove this hardcoding later)
          REMOTE_HOST="ec2-user@13.239.232.171"
          
          echo "Connecting to host: $REMOTE_HOST"
          
          # Try to verify SSH port is open
          nc -zv $(echo $REMOTE_HOST | cut -d '@' -f2) 22 || echo "Warning: Cannot verify if port 22 is open"
          
          # Add retry logic for ssh-keyscan with the hardcoded IP
          EC2_IP="13.239.232.171"
          for i in {1..3}; do
            echo "Attempt $i: Running ssh-keyscan..."
            if ssh-keyscan -T 10 $EC2_IP >> ~/.ssh/known_hosts; then
              echo "✓ Successfully added host to known_hosts"
              break
            else
              echo "× ssh-keyscan failed, retrying in 3 seconds..."
              sleep 3
            fi
          done
          
          # Test connection with verbose output
          echo "Testing SSH connection directly..."
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $REMOTE_HOST "echo Connection successful"

      - name: Deploy to EC2
        run: |
          # Create deployment package
          tar -czf deploy.tar.gz .env docker-compose.yml API/ frontend/ image-recognition/ db/ nginx/
          
          # Transfer files
          scp -i ~/.ssh/id_rsa deploy.tar.gz ${{ secrets.EC2_HOST }}:~/flowscan-app/
          
          # Execute deployment commands
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_HOST }} "
            cd ~/flowscan-app && 
            tar -xzf deploy.tar.gz && 
            # Add AWS credentials for container itself
            echo 'AWS_ACCESS_KEY_ID=${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}' >> .env &&
            echo 'AWS_SECRET_ACCESS_KEY=${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}' >> .env &&
            echo 'AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }}' >> .env &&
            # Deploy with Docker Compose
            docker-compose down &&
            docker-compose pull || true &&
            docker-compose build --no-cache &&
            docker-compose up -d
          "